-- CREATE TABLE students (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     email VARCHAR(100),
--     class VARCHAR(50),
--     roll_number VARCHAR(50),
--     list VARCHAR(100) NOT NULL
-- );

-- CREATE TABLE attendance (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     student_id INT,
--     date DATE,
--     status ENUM('Present', 'Absent'),
--     FOREIGN KEY (student_id) REFERENCES students(id)
-- );
